### ISSUE TITLE
doesn't build

### ISSUE THREAD

**Issue by steveschow** [kimsand/Jupiter80Librarian#2]
doesn't build.  Code signing required.  Turned off code signing and got many other build errors..

**Comment by kimsand** [comment]
Can you list a couple of errors? Do you have the latest release version of Xcode (7.3.1)? Older and newer (beta) versions have different versions of Swift embedded, which might produce errors. This problem will go away when Swift is stabilised.

**Comment by steveschow** [comment]
I'm on mavericks, which means xcode 6.2 is the newest version.  If your software requires a newer version of Xcode in order to be built, then it means a newer version of OSX must be used to build it.  Perhaps you can clarify this requirement in your readme.

There are several hundred errors reported during compile, I'm trying to figure out how to copy and paste them here, but can't seem to find a way.  I'm generally not a fan of xcode, which is why I don't know how to use it very well I guess.

It definitely looks like a lot of swift errors, so it sounds like this project requires a newer version of OSX to build

**Comment by kimsand** [comment]
The project is continuously being updated to match the latest Swift syntax. This means the latest release version of Xcode is required to build the project until Swift is stabilised. I will add this requirement to the README.
